#!/bin/bash

# set -x

mkdir -p counters300

function marker {
	pnmtopng tmp/${1}_a.ppm > counters300/$2.a.png
	pnmtopng tmp/${1}_b.ppm > counters300/$2.b.png
}

function marker2 {
	pnmtopng tmp/${1}_a.ppm > counters300/$2.png
	pnmtopng tmp/${1}_b.ppm > counters300/$3.png
}

marker2 cs_circle_1_1_1 marker_battle marker_storm
marker2 cs_circle_1_1_2 marker_levy marker_campaign
marker2 cs_circle_1_1_3 marker_victory_teutonic marker_victory_half_teutonic
marker2 cs_circle_1_1_4 marker_victory_russian marker_victory_half_russian
marker2 cs_circle_1_1_5 marker_enemy_lords_removed_teutonic marker_pleskau_blue
marker2 cs_circle_1_1_6 marker_enemy_lords_removed_russian marker_pleskau_gray

marker2 cs_sq_small_1_1_2 marker_ravaged_teutonic marker_ravaged_russian

marker cs_sq_small_1_1_1 unit_men_at_arms
marker cs_sq_small_3_1_1 unit_knights
marker cs_sq_small_3_1_3 unit_asiatic_horse
marker cs_sq_small_3_1_4 unit_militia
marker cs_sq_small_3_3_1 unit_light_horse
marker cs_sq_small_3_3_3 unit_serfs
marker cs_sq_small_3_5_1 unit_sergeants

marker2 cs_sq_large_1_1_7 marker_conquered_teutonic marker_conquered_russian
marker2 cs_sq_large_1_4_11 marker_moved_fought marker_supply_source
marker2 cs_sq_large_2_1_1 marker_siege_teutonic marker_siege_russian
marker cs_sq_large_2_1_8 marker_walls

marker2 cs_sq_large_2_1_10 marker_1_teutonic marker_1_russian
marker2 cs_sq_large_2_1_11 marker_2_teutonic marker_2_russian
marker2 cs_sq_large_2_1_12 marker_3_teutonic marker_3_russian
marker2 cs_sq_large_2_2_10 marker_4_teutonic marker_4_russian
marker2 cs_sq_large_2_2_11 marker_5_teutonic marker_5_russian
marker2 cs_sq_large_2_2_12 marker_6_teutonic marker_6_russian

marker2 cs_sq_large_1_1_2 asset_coin_x1 asset_coin_x2
marker2 cs_sq_large_1_3_1 asset_coin_x3 asset_coin_x4

marker2 cs_sq_large_1_3_3 asset_loot_x1 asset_loot_x2
marker2 cs_sq_large_1_4_6 asset_loot_x3 asset_loot_x4

marker2 cs_sq_large_1_5_1 asset_prov_x1 asset_prov_x2
marker2 cs_sq_large_3_4_10 asset_prov_x3 asset_prov_x4

marker2 cs_sq_large_3_1_1 asset_boat_x1 asset_ship_x1
marker2 cs_sq_large_3_4_1 asset_boat_x2 asset_ship_x2
marker2 cs_sq_large_3_4_2 asset_boat_x4 asset_ship_x4

marker2 cs_sq_large_3_1_7 asset_sled_x1 asset_cart_x1
marker2 cs_sq_large_3_4_4 asset_sled_x2 asset_cart_x2
marker2 cs_sq_large_3_5_6 asset_sled_x4 asset_cart_x4

marker cs_rect_1_1_1 marker_sea_trade_blocked

marker cs_rect_2_1_1 lord_russian_aleksandr
marker cs_rect_2_1_2 lord_russian_andrey
marker cs_rect_2_1_3 vassal_russian_gavrilo_pskov
marker cs_rect_2_1_4 vassal_russian_andrey_vladimir
marker cs_rect_2_1_5 vassal_russian_domash_novgorod
marker cs_rect_2_1_6 vassal_russian_andrey_kipchaqs
marker cs_rect_2_1_7 vassal_teutonic_knud_and_abel_dietrich_von_kivel

marker cs_rect_2_2_1 lord_russian_vladislav
marker cs_rect_2_2_2 lord_russian_karelians
marker cs_rect_2_2_3 vassal_russian_aleksandr_pereyaslavl
marker cs_rect_2_2_4 vassal_russian_andrey_suzdal
marker cs_rect_2_2_5 lord_teutonic_andreas
marker cs_rect_2_2_6 vassal_teutonic_andreas_summer_crusaders
marker cs_rect_2_2_7 vassal_teutonic_knud_and_abel_otto_von_luneburg

marker cs_rect_2_3_1 lord_russian_domash
marker cs_rect_2_3_2 vassal_russian_vladislav_vepsian_auxiliaries
marker cs_rect_2_3_3 vassal_russian_aleksandr_rostov
marker cs_rect_2_3_4 vassal_teutonic_hermann_ugaunian_auxiliaries
marker cs_rect_2_3_5 lord_teutonic_hermann
marker cs_rect_2_3_6 lord_teutonic_knud_and_abel
marker cs_rect_2_3_7 vassal_teutonic_knud_and_abel_estonian_auxiliaries

marker cs_rect_2_4_1 lord_russian_gavrilo
marker cs_rect_2_4_2 vassal_russian_vladislav_ingrian_auxiliaries
marker cs_rect_2_4_3 vassal_russian_aleksandr_yaroslavl
marker cs_rect_2_4_4 vassal_teutonic_hermann_helmond_von_luneburg
marker cs_rect_2_4_5 lord_teutonic_heinrich
marker cs_rect_2_4_6 lord_teutonic_yaroslav
marker2 cs_rect_2_4_7 marker_castle_teutonic marker_castle_russian

marker cs_rect_2_5_1 vassal_russian_vladislav_vodian_auxiliaries
marker cs_rect_2_5_2 vassal_russian_vladislav_izhoran_auxiliaries
marker cs_rect_2_5_3 vassal_russian_aleksandr_mongols
marker cs_rect_2_5_4 vassal_teutonic_hermann_johannes_von_dolen
marker cs_rect_2_5_5 lord_teutonic_rudolf
marker cs_rect_2_5_6 vassal_teutonic_rudolf_summer_crusaders
#marker2 cs_rect_2_5_7 marker_castle_teutonic marker_castle_russian

marker cs_rect_2_6_1 vassal_russian_gavrilo_borderland_russians
marker cs_rect_2_6_2 vassal_russian_domash_novgorod
#marker cs_rect_2_6_3 vassal_russian_aleksandr_mongols
marker cs_rect_2_6_4 vassal_teutonic_heinrich_odward_von_lode
marker cs_rect_2_6_5 vassal_teutonic_andreas_teutonic_vassals
marker cs_rect_2_6_6 vassal_teutonic_rudolf_ex_sword_brethren
marker cs_rect_2_6_7 vassal_teutonic_yaroslav_mstislavich_partisans

marker cs_rect_2_7_1 vassal_russian_gavrilo_pskov_militia
marker cs_rect_2_7_2 vassal_russian_domash_novgorod
#marker cs_rect_2_7_3 vassal_russian_andrey_kipchaqs
marker cs_rect_2_7_4 vassal_teutonic_heinrich_heinrich_von_lode
marker cs_rect_2_7_5 vassal_teutonic_andreas_lettgallian_auxiliaries
marker cs_rect_2_7_6 vassal_teutonic_rudolf_jerwen_teutonic_vassals
marker2 cs_rect_2_7_7 marker_pursuit_teutonic marker_pursuit_russian
